### PR TITLE
Updated README.MD (sudo need to get permission)

### PR DESCRIPTION
**Pull request by Loghijiaha**

### CODE REVIEW

**Comment by lastlegion** [comment]
It depends on how you install `npm`. Ideally you shouldn't need `sudo`.

**Comment by birm** [comment]
That's true, but I'm not sure how many people follow [those steps](https://stackoverflow.com/questions/18088372/how-to-npm-install-global-not-as-root). Should we document how to set that up instead of just throwing sudo there?

**Comment by lastlegion** [comment]
Hmm if we were to make an assumption it should be that node is properly installed. 

A similar case is docker. Anytime people include some docker specific documentation, they assume that docker is available without sudo.

**Comment by lastlegion** [comment]
Anyways all the best with your Datascope adventure @Loghijiaha! 😃

**Comment by Loghijiaha** [comment]
Welcome @lastlegion😄

**Pull request merged**
